Repository bosnet/sebak, pull requests merged in 2018-09, with the labels that each got.

#314 Using API blueprint for API document
  docs/API.md
  docs/README.md
  docs/v1/accounts.md
  docs/v1/models.md
Labels: API

#325 received data may not ordered. do not check the sequence
  lib/api_test.go
Labels: bug

#328 Modify `Round` package `sebak` to `round`
  lib/ballot.go
  lib/ballot_test.go
  lib/block.go
  lib/block_header.go
  lib/isaac.go
  lib/isaac_simulation_test.go
  lib/node_runner.go
  lib/proposer_calculator_test.go
  lib/round/round.go
  lib/round_vote.go
  lib/running_round.go
  lib/test.go
Labels: enhancement

#323 EventStream
  lib/api_stream.go
  lib/api_stream_test.go
Labels: API

#333 rename package `sebaknode` to `node`
  cmd/sebak/cmd/run.go
  lib/api.go
  lib/api_node_test.go
  lib/ballot.go
  lib/ballot_test.go
  lib/isaac.go
  lib/network/base.go
  lib/network/connection_manager.go
  lib/network/http2_network_client.go
  lib/network/memory_network_client.go
  lib/network/memory_network_test.go
  lib/node/localNode.go
  lib/node/node.go
  lib/node/node_state.go
  lib/node/node_state_test.go
  lib/node/node_test.go
  lib/node/queue.go
  lib/node/validator.go
  lib/node/validator_test.go
  lib/node_runner.go
  lib/node_runner_ballot_transaction_checker.go
  lib/node_runner_checker.go
  lib/node_runner_message_checker.go
  lib/node_runner_test.go
  lib/test.go
Labels: enhancement

#336 Using eventstream with APIHandlers
  lib/api.go
  lib/api_account.go
  lib/api_stream.go
  lib/api_transaction.go
  lib/block_operation.go
  lib/block_transaction.go
  lib/httputils/httputils.go
  lib/httputils/json.go
Labels: API

#319 API response (HAL+JSON)
  lib/api/resource.go
  lib/api/resource_test.go
Labels: API

#320 http problem
  lib/api_test.go
  lib/error/http_problem.go
Labels: enhancement

#332 Rename package `sebakstorage` to `storage
  cmd/sebak/cmd/genesis.go
  cmd/sebak/cmd/run.go
  lib/api.go
  lib/api/resource_test.go
  lib/api_node_test.go
  lib/api_test.go
  lib/ballot.go
  lib/block.go
  lib/block/account.go
  lib/block/account_test.go
  lib/block_operation.go
  lib/block_operation_test.go
  lib/block_transaction.go
  lib/block_transaction_history.go
  lib/block_transaction_test.go
  lib/common/message.go
  lib/node_runner.go
  lib/node_runner_test.go
  lib/operation.go
  lib/operation_create_account.go
  lib/operation_payment.go
  lib/statedb/statedb_test.go
  lib/storage/dbbackend.go
  lib/storage/leveldb.go
  lib/storage/leveldb_test.go
  lib/storage/statedb.go
  lib/storage/statedb_test.go
  lib/storage/storage.go
  lib/storage/test.go
  lib/test.go
  lib/transaction.go
  lib/trie/database.go
Labels: enhancement

#140 Replace checkpoints with sequence ID
  cmd/sebak/cmd/genesis.go
  cmd/sebak/cmd/wallet/payment.go
  lib/api/resource.go
  lib/api/resource_test.go
  lib/api_node_test.go
  lib/api_stream_test.go
  lib/ballot.go
  lib/block/account.go
  lib/block/account_test.go
  lib/block/test.go
  lib/block_operation.go
  lib/block_operation_test.go
  lib/block_transaction.go
  lib/block_transaction_test.go
  lib/common/util.go
  lib/error/errors.go
  lib/node_runner_checker_test.go
  lib/node_runner_memory_network_test.go
  lib/node_runner_test.go
  lib/operation_create_account.go
  lib/operation_payment.go
  lib/statedb/state_object.go
  lib/statedb/statedb.go
  lib/test.go
  lib/transaction.go
  lib/transaction_checker.go
  lib/transaction_test.go
  tests/account-creation/request_1_2821_create_account_1.json
  tests/account-creation/request_2_2822_pay_to_account_1.json
Labels: enhancement

#345 Refactoring log part and Support JSON log output
  cmd/sebak/cmd/run.go
  lib/api_node.go
  lib/api_node_test.go
  lib/ballot.go
  lib/common/log.go
  lib/common/message.go
  lib/common/voting.go
  lib/init.go
  lib/isaac_simulation_test.go
  lib/network/base.go
  lib/network/connection_manager.go
  lib/network/http2_network.go
  lib/network/http2_network_config.go
  lib/network/http2_network_test.go
  lib/network/init.go
  lib/network/init_test.go
  lib/network/memory_network.go
  lib/network/memory_network_client.go
  lib/network/memory_network_test.go
  lib/node_runner.go
  lib/node_runner_checker.go
  lib/node_runner_checker_test.go
  lib/node_runner_message_checker.go
  lib/node_runner_message_checker_test.go
  lib/node_runner_test.go
  lib/test.go
  lib/voting_policy.go
Labels: enhancement

#343 Post transaction handler for client API
  lib/api.go
  lib/node_runner.go
Labels: API

#337 Page support
  lib/block/account.go
  lib/block/account_test.go
  lib/block/ballot.go
  lib/block/block.go
  lib/block/operation.go
  lib/block/operation_test.go
  lib/block/test.go
  lib/block/transaction.go
  lib/block/transaction_test.go
  lib/common/util.go
  lib/consensus/isaac.go
  lib/network/api/account.go
  lib/network/api/api_test.go
  lib/network/api/resource_test.go
  lib/network/api/transaction.go
  lib/storage/leveldb.go
  lib/storage/leveldb_test.go
  lib/storage/statedb.go
  lib/storage/storage.go
Labels: enhancement

#361 WriteJSON support hal.Resource
  lib/network/httputils/json.go
Labels: API

#347 refactor prefix to make it short
  lib/block/account.go
  lib/block/block.go
  lib/block/operation.go
  lib/block/transaction.go
  lib/common/prefix.go
Labels: enhancement

#348 Merging HTTP Logs(Combined and Error) To Log15
  Gopkg.lock
  cmd/sebak/cmd/run.go
  lib/network/http2.go
  lib/network/http2_config.go
  lib/network/http2_config_test.go
  lib/network/http2_network_log.go
  lib/network/http2_test.go
  lib/node/runner/api_node_test.go
  lib/node/runner/init_test.go
  lib/node/runner/node_runner_test.go
Labels: enhancement

#349 Add LevelDB.Walk to support cursor
  lib/storage/leveldb.go
  lib/storage/leveldb_test.go
Labels: enhancement

#365 Revise APIs
  lib/block/account.go
  lib/block/block.go
  lib/block/operation.go
  lib/block/transaction.go
  lib/network/api/account.go
  lib/network/api/account_test.go
  lib/network/api/api.go
  lib/network/api/api_test.go
  lib/network/api/httpproblem/http_problem.go
  lib/network/api/httpproblem/http_problem_test.go
  lib/network/api/operation.go
  lib/network/api/operation_test.go
  lib/network/api/resource/resource.go
  lib/network/api/resource/resource_test.go
  lib/network/api/stream.go
  lib/network/api/test.go
  lib/network/api/transaction.go
  lib/network/api/transaction_test.go
  lib/network/api/util.go
  lib/node/runner/node_runner.go
  lib/storage/leveldb.go
Labels: API

#373 Fix WriteHeader Content-Type typo
  lib/network/httputils/json.go
Labels: API, bug

#369 Add Client Api Version (/api/v1/)
  lib/network/api/api.go
  lib/node/runner/node_runner.go
  tests/utils.sh
Labels: API

#371 Write API blueprint
  docs/API.md
  docs/v1/accounts.md
  docs/v1/models.md
  docs/v1/transactions.md
Labels: API

#378 Fix MSON models and apply aglio for api rendering
  docs/API.md
  docs/v1/models.md
Labels: API

#380 Add /transactions/{hash}/operations handler
  docs/v1/transactions.md
  lib/block/operation.go
  lib/network/api/api.go
  lib/network/api/resource/resource.go
  lib/network/api/test.go
  lib/network/api/tx_operations.go
  lib/network/api/tx_operations_test.go
  lib/node/runner/node_runner.go
Labels: API

#393 Add Problem resource to api doc
  docs/v1/accounts.md
  docs/v1/models.md
Labels: API

#396 `/api/v1/account` to `/api/v1/accounts`
  cmd/sebak/cmd/wallet/payment.go
  docs/v1/accounts.md
  lib/network/api/api.go
  tests/utils.sh
Labels: API

#405 Do not panic on wrong operation body
  lib/transaction/operation.go
Labels: bug

#422 Rename `ExistBlockXXX` to `ExistsBlock`
  lib/block/account.go
  lib/block/account_test.go
  lib/block/operation.go
  lib/block/operation_test.go
  lib/block/transaction.go
  lib/block/transaction_test.go
  lib/network/api/account.go
  lib/network/api/transaction.go
  lib/node/runner/checker_ballot_transaction.go
Labels: enhancement

#415 Remove `Broadcaster` and `ProposerCalculator` interface and make `connectionManager` interface
  cmd/sebak/cmd/run.go
  lib/consensus/isaac.go
  lib/consensus/proposer_selector.go
  lib/network/connection_manager.go
  lib/network/validator_connection_manager.go
  lib/node/runner/api_node_test.go
  lib/node/runner/broadcaster_test.go
  lib/node/runner/isaac_simulation_test.go
  lib/node/runner/isaac_state_manager.go
  lib/node/runner/isaac_state_transit_test.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/proposer_selector_test.go
  lib/node/runner/test.go
  lib/node/runner/test_connection_manager.go
Labels: enhancement

#437 Doc: Add paging section (api)
  docs/API.md
  docs/v1/paging.md
Labels: API, Doc

#442 Add empty transaction test
  lib/node/runner/isaac_voting_empty_transaction_test.go
Labels: Consensus, enhancement

#421 Get The Missing Transactions From Proposer
  lib/error/base.go
  lib/error/errors.go
  lib/node/runner/api_block.go
  lib/node/runner/api_block_options.go
  lib/node/runner/api_block_test.go
  lib/node/runner/api_node.go
  lib/node/runner/api_transaction.go
  lib/node/runner/api_transactions_test.go
  lib/node/runner/node_runner.go
Labels: API

#452 Fixed the empty `Ballot.H.Hash`
  lib/ballot/ballot_test.go
  lib/error/base.go
  lib/error/base_test.go
Labels: bug

#446 Checking `BaseReserve` for new created account
  lib/block/account.go
  lib/block/test.go
  lib/common/constant.go
  lib/error/errors.go
  lib/node/runner/api_node_test.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/test.go
  lib/transaction/operation_create_account.go
  lib/transaction/operation_create_account_test.go
  tests/overdraft/request_1_2821_create_account_1.json
  tests/overdraft/request_1_2821_create_account_1.json.check
  tests/overdraft/request_2_2821_no_amount_tx.json
  tests/overdraft/request_2_2821_no_amount_tx.json.check
  tests/overdraft/request_3_2823_one_gon_payment.json.check
  tests/overdraft/request_4_2823_overdraft_by_99.json
  tests/overdraft/request_4_2823_overdraft_by_99.json.check
  tests/overdraft/request_5_2821_overdraft_by_1.json
  tests/overdraft/request_5_2821_overdraft_by_1.json.check
  tests/overdraft/request_6_2821_emptying_account.json
Labels: bug

#453 Genesis block should have valid transaction
  cmd/sebak/cmd/genesis.go
  lib/block/block.go
  lib/block/block_test.go
  lib/common/constant.go
  lib/node/runner/api_node_test.go
  lib/node/runner/isaac_voting_empty_transaction_test.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/test.go
  lib/transaction/operation.go
Labels: enhancement

#454 Set `BlockTransaction.Confirmed` by `Block.Confirmed`
  lib/block/block.go
  lib/block/operation_test.go
  lib/block/test.go
  lib/block/transaction.go
  lib/block/transaction_test.go
  lib/network/api/operation.go
  lib/network/api/resource/resource_test.go
  lib/network/api/test.go
  lib/network/api/transaction.go
  lib/network/api/transaction_test.go
  lib/network/api/tx_operations.go
  lib/network/api/tx_operations_test.go
  lib/node/runner/api_block_test.go
  lib/node/runner/api_transactions_test.go
  lib/node/runner/checker.go
  lib/storage/options.go
Labels: bug
