Repository bosnet/sebak, pull requests merged in 2018-12, with the labels that each got.

#742 Make long-term test enhanced
  .circleci/config.yml
  tests/block-time/Dockerfile
  tests/block-time/README.md
  tests/block-time/block-time.sh
  tests/block-time/entrypoint.sh
  tests/block-time/run.sh
  tests/block-time/utils.sh
  tests/long-term/block-time.sh
  tests/long-term/entrypoint.sh
  tests/long-term/run.sh
  tests/long-term/sync.sh
  tests/node/run.sh
Labels: Testing

#859 block.Confirmed is updated when it is empty
  lib/block/block.go
Labels: bug, sync

#860 Allow watch with Watcher node
  lib/sync/config.go
  lib/sync/watcher.go
Labels: sync

#848 Operation Resource `self` to /transactions/{txhash}/operations/{id}
  lib/block/operation.go
  lib/block/operation_test.go
  lib/block/test.go
  lib/block/transaction.go
  lib/client/client.go
  lib/common/observer/observer.go
  lib/errors/errors.go
  lib/node/runner/api/api.go
  lib/node/runner/api/base_test.go
  lib/node/runner/api/operation.go
  lib/node/runner/api/operation_test.go
  lib/node/runner/api/resource/constant.go
  lib/node/runner/api/resource/operation.go
  lib/node/runner/api/resource/resource_test.go
  lib/node/runner/api/tx_operations.go
  lib/node/runner/block_operations.go
  lib/node/runner/node_runner.go
Labels: API

#865 Support stage (-rcXXX) with bumpversion
  .bumpversion.cfg
Labels: enhancement

#876 Set `formatted` field at default rate
  cmd/sebak/cmd/cmd_test.go
  lib/common/constant.go
Labels: bug

#705 #659 Adaptable Discoverying Nodes
  cmd/sebak/cmd/cmd_test.go
  cmd/sebak/cmd/run.go
  docker/node1.env
  docker/node2.env
  docker/node3.env
  docker/node4.env
  lib/common/config.go
  lib/common/constant.go
  lib/common/message.go
  lib/common/net.go
  lib/errors/errors.go
  lib/network/base.go
  lib/network/connection_manager.go
  lib/network/discovery_message.go
  lib/network/discovery_message_test.go
  lib/network/http2.go
  lib/network/http2_client.go
  lib/network/memory.go
  lib/network/memory_client.go
  lib/network/memory_test.go
  lib/network/validator_connection_manager.go
  lib/node/local_node.go
  lib/node/runner/api_discovery.go
  lib/node/runner/api_node.go
  lib/node/runner/api_node_test.go
  lib/node/runner/isaac_state_transit_test.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/post_transaction_test.go
  lib/node/runner/test.go
  lib/node/runner/test_connection_manager.go
  lib/node/validator.go
  lib/sync/fetcher.go
  lib/sync/fetcher_test.go
  lib/sync/mock_test.go
  lib/sync/watcher.go
Labels: enhancement

#883 load CommonAccountAddress with sync start
  cmd/sebak/cmd/run.go
  lib/sync/config.go
  lib/sync/config_test.go
Labels: Urgent, bug, sync
