Repository bosnet/sebak, pull requests merged in 2018-11, with the labels that each got.

#627 Fill the `block.total-ops` in node info API
  lib/node/runner/api/node_info.go
  lib/node/runner/api/node_info_test.go
Labels: bug

#633 Disable noisy colored log
  cmd/sebak/cmd/run.go
  go.mod
  go.sum
Labels: enhancement

#635 Fixed to find transactions from `transaction.Pool` and also `block.TransactionPool`
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/node_runner.go
Labels: bug

#636 Wrong Error In `runner.MessageHasSameSource`
  lib/errors/errors.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/checker_message.go
  lib/node/runner/checker_test.go
Labels: bug

#641 Stop broadcasting the incoming transaction in `/node/message`
  lib/node/runner/api/transaction_post.go
  lib/node/runner/api_node.go
  lib/node/runner/node_runner.go
  tests/node/default_runner.sh
Labels: enhancement

#615 Saving `BlockOperation`s after `finishBallot()`
  lib/block/block.go
  lib/block/genesis.go
  lib/block/transaction.go
  lib/block/transaction_test.go
  lib/errors/errors.go
  lib/network/validator_connection_manager.go
  lib/node/runner/api/resource/resource_test.go
  lib/node/runner/api/test.go
  lib/node/runner/api_block_test.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/block_operations.go
  lib/node/runner/block_operations_test.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/finish_ballot.go
  lib/node/runner/node_runner.go
  lib/node/runner/util.go
  lib/storage/leveldb.go
  lib/sync/fetcher_test.go
  lib/transaction/test.go
  lib/transaction/transaction.go
Labels: enhancement

#642 Add more logging and wrap errors
  go.mod
  lib/errors/errors.go
  lib/sync/fetcher.go
Labels: sync

#653 Check 'fee' by operation type
  lib/ballot/proposer_transaction.go
  lib/client/client.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/transaction/operation/collect_tx_fee.go
  lib/transaction/operation/congress_voting.go
  lib/transaction/operation/congress_voting_result.go
  lib/transaction/operation/create_account.go
  lib/transaction/operation/operation.go
  lib/transaction/operation/operation_inflation.go
  lib/transaction/operation/payment.go
  lib/transaction/operation/unfreezing_request.go
  lib/transaction/transaction.go
  lib/transaction/transaction_test.go
Labels: bug

#658 Zero division error in `common.Amount.MultUint64()`
  lib/common/amount.go
Labels: bug

#657 Sending `Transaction` must use `/api/v1/transactions`
  cmd/sebak/cmd/wallet/payment.go
  cmd/sebak/cmd/wallet/unfreezeRequest.go
  lib/network/base.go
  lib/network/http2_client.go
  lib/network/memory_client.go
Labels: bug

#645 Surpass error when genesis block is already created
  cmd/sebak/cmd/genesis.go
  lib/node/runner/util.go
Labels: enhancement

#655 Failed to save `BlockOperation`s
  lib/node/runner/block_operations.go
  lib/node/runner/block_operations_test.go
Labels: bug

#673 Use double linked list in place of slice for hash list in tx pool
  lib/transaction/pool.go
Labels: enhancement

#699 Rename "order" to reverse in client API
  lib/client/client.go
  lib/node/runner/api/account.go
  lib/node/runner/api/operation.go
  lib/node/runner/api/transaction.go
  lib/node/runner/api/tx_operations.go
  lib/node/runner/api_block_options.go
  lib/storage/options.go
Labels: bug

#692 ricardian contract with yaml format
  docs/ricardian._sample.yaml
  docs/ricardian.md
  docs/ricardian_guide.md
  docs/ricardian_sample.md
Labels: enhancement

#710 Change metric_path to /metrics
  lib/network/http2.go
Labels: API

#711 Modify consensus in sync
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/checker.go
  lib/node/runner/finish_ballot.go
  lib/node/runner/finish_ballot_test.go
Labels: bug

#672 PageQuery for api resource list and storage list options
  lib/node/runner/api/account.go
  lib/node/runner/api/operation.go
  lib/node/runner/api/pagequery.go
  lib/node/runner/api/transaction.go
  lib/node/runner/api/transaction_history.go
  lib/node/runner/api/tx_operations.go
Labels: API

#714 Fix ricardian contract format
  docs/ricardian._sample.yaml
  docs/ricardian_guide.md
Labels: Congress Voting

#634 HTTP cache middleware
  cmd/sebak/cmd/run.go
  go.mod
  go.sum
  lib/common/config.go
  lib/common/constant.go
  lib/network/httpcache/client.go
  lib/network/httpcache/client_test.go
  lib/network/httpcache/config.go
  lib/network/httpcache/mem.go
  lib/network/httpcache/mem_test.go
  lib/network/httpcache/nop.go
  lib/network/httpcache/redis.go
  lib/network/httpcache/redis_test.go
  lib/network/httpcache/types.go
  lib/node/runner/node_runner.go
Labels: API

#721 Support CIDR in rate-limit
  cmd/sebak/cmd/run.go
  lib/network/http_middlewares.go
  lib/network/http_middlewares_test.go
Labels: Urgent, enhancement

#723 Failed to save `BlockOperation`
  lib/block/transaction.go
  lib/node/runner/block_operations.go
  lib/node/runner/block_operations_test.go
Labels: Urgent, bug

#728 Reopen: Support CIDR in rate-limit
  lib/network/http_middlewares.go
Labels: Urgent, bug

#736 fix amount rlp
  lib/common/amount.go
  lib/common/amount_test.go
  lib/transaction/operation/operation_test.go
  tests/long-term/create_account/request_1_2821_create_10.json
  tests/long-term/payment_1/request_10_2823_pay_9.json
  tests/long-term/payment_1/request_11_2823_pay_10.json
  tests/long-term/payment_1/request_2_2822_pay_1.json
  tests/long-term/payment_1/request_3_2823_pay_2.json
  tests/long-term/payment_1/request_4_2821_pay_3.json
  tests/long-term/payment_1/request_5_2823_pay_4.json
  tests/long-term/payment_1/request_6_2821_pay_5.json
  tests/long-term/payment_1/request_7_2821_pay_6.json
  tests/long-term/payment_1/request_8_2822_pay_7.json
  tests/long-term/payment_1/request_9_2822_pay_8.json
  tests/long-term/payment_2/request_10_2823_pay_9.json
  tests/long-term/payment_2/request_11_2824_pay_10.json
  tests/long-term/payment_2/request_2_2824_pay_1.json
  tests/long-term/payment_2/request_3_2823_pay_2.json
  tests/long-term/payment_2/request_4_2821_pay_3.json
  tests/long-term/payment_2/request_5_2823_pay_4.json
  tests/long-term/payment_2/request_6_2821_pay_5.json
  tests/long-term/payment_2/request_7_2821_pay_6.json
  tests/long-term/payment_2/request_8_2822_pay_7.json
  tests/long-term/payment_2/request_9_2822_pay_8.json
  tests/node/account-creation/request_1_2821_create_account_1.json
  tests/node/account-creation/request_2_2822_pay_to_account_1.json
  tests/node/overdraft/request_1_2821_create_account_1.json
  tests/node/overdraft/request_2_2821_no_amount_tx.json
  tests/node/overdraft/request_3_2823_one_gon_payment.json
  tests/node/overdraft/request_4_2823_overdraft_by_99.json
  tests/node/overdraft/request_5_2821_overdraft_by_1.json
  tests/node/overdraft/request_6_2821_emptying_account.json
Labels: bug

#738 Move setting sync to consensus to saveBlock method
  lib/node/runner/checker.go
Labels: bug

#740 Fix wrong state transit order
  lib/node/runner/isaac_state_manager.go
Labels: bug

#739 Modify to not call `NextHeight` if saveBlock fails
  lib/node/runner/checker.go
Labels: bug

#741 Stop sending ballot in sync
  lib/node/runner/isaac_state_manager.go
Labels: enhancement

#719 inflation pf
  docker/node1.env
  docker/node2.env
  docker/node3.env
  docker/node4.env
  docker/self.env
  lib/client/response.go
  lib/common/config.go
  lib/errors/errors.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/checker_ballot_transaction_test.go
  lib/node/runner/checker_message.go
  lib/node/runner/checker_test.go
  lib/node/runner/finish_ballot.go
  lib/node/runner/isaac_simulation_unfreezing_test.go
  lib/node/runner/isaac_state_manager.go
  lib/node/runner/modified_source_validate_test.go
  lib/node/runner/node_runner.go
  lib/sync/validator.go
  lib/transaction/operation/congress_voting.go
  lib/transaction/operation/congress_voting_result.go
  lib/transaction/operation/operation.go
  lib/transaction/operation/operation_inflation_pf.go
  lib/transaction/operation/operation_test.go
  lib/transaction/transaction_test.go
  tests/client/congressvoting_inflationpf_test.go
  tests/client/congressvoting_test.go
  tests/client/run.sh
  tests/long-term/accounts.sh
  tests/node/run.sh
Labels: Urgent

#709 681 congress address handle
  cmd/sebak/cmd/run.go
  docker/node1.env
  docker/node2.env
  docker/node3.env
  docker/node4.env
  docker/self.env
  lib/errors/errors.go
  lib/node/runner/checker_ballot_transaction.go
  lib/transaction/operation/congress_voting.go
  lib/transaction/operation/congress_voting_result.go
  lib/transaction/transaction_test.go
Labels: Congress Voting, Urgent

#708 Apply metrics
  cmd/sebak/cmd/run.go
  go.mod
  go.sum
  lib/metrics/api.go
  lib/metrics/consensus.go
  lib/metrics/constant.go
  lib/metrics/prom.go
  lib/metrics/sync.go
  lib/metrics/txpool.go
  lib/metrics/vars.go
  lib/metrics/version.go
  lib/network/http2.go
  lib/network/http2_network_log.go
  lib/network/validator_connection_manager.go
  lib/node/runner/finish_ballot.go
  lib/node/runner/isaac_state_manager.go
  lib/sync/fetcher.go
  lib/sync/syncer.go
  lib/transaction/pool.go
Labels: observability

#753 Add MaxLimitExceed check
  lib/errors/errors.go
  lib/node/runner/api/pagequery.go
Labels: API

#744 Txpool Limit
  cmd/sebak/cmd/run.go
  lib/common/config.go
  lib/common/constant.go
  lib/errors/errors.go
  lib/network/httputils/httputils.go
  lib/node/runner/api_node.go
  lib/node/runner/api_transactions_test.go
  lib/node/runner/checker_message.go
  lib/node/runner/node_runner.go
  lib/node/runner/test.go
  lib/transaction/pool.go
Labels: enhancement

#732 Add /blocks , /blocks/{hashOrHeight} APIs
  docs/API.md
  docs/API_v1/blocks.md
  docs/API_v1/models.md
  lib/block/block.go
  lib/errors/errors.go
  lib/network/httputils/httputils.go
  lib/node/runner/api/api.go
  lib/node/runner/api/base_test.go
  lib/node/runner/api/block.go
  lib/node/runner/api/block_test.go
  lib/node/runner/api/blocks.go
  lib/node/runner/api/blocks_test.go
  lib/node/runner/api/pagequery.go
  lib/node/runner/api/resource/block.go
  lib/node/runner/api/resource/constant.go
  lib/node/runner/node_runner.go
  lib/storage/leveldb.go
  lib/storage/leveldb_test.go
Labels: API

#743 Fix #682: no fee for frozen account related operations
  cmd/sebak/cmd/wallet/payment.go
  cmd/sebak/cmd/wallet/unfreezeRequest.go
  lib/block/account.go
  lib/common/constant.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/checker_ballot_transaction_test.go
  lib/node/runner/checker_test.go
  lib/node/runner/isaac_simulation_unfreezing_test.go
  lib/node/runner/test.go
  lib/transaction/operation/create_account.go
  lib/transaction/operation/unfreezing_request.go
  lib/transaction/test.go
  tests/client/account_test.go
  tests/client/congressvoting_inflationpf_test.go
  tests/client/freezing_test.go
  tests/client/run.sh
  tests/client/self.env
  tests/client/test.go
Labels: frozen

#759 Sending Invalid transaction message should get `BadRequest`(400) error code
  lib/node/runner/api/transaction_post.go
  lib/node/runner/post_transaction_test.go
Labels: bug

#746 Add unfreezing period to node info
  lib/node/info.go
  lib/node/runner/api/node_info_test.go
  lib/node/runner/util.go
Labels: API, frozen

#769 Update ricardian contract sample as valid yaml
  docs/ricardian._sample.yaml
Labels: Contract, Doc

#745 Skip broadcasting self-signed Ballot
  lib/ballot/ballot.go
  lib/consensus/isaac.go
  lib/network/validator_connection_manager.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/checker.go
  lib/node/runner/checker_test.go
  lib/node/runner/node_runner.go
Labels: enhancement

#782 Make sync log more readable
  lib/node/runner/checker.go
  lib/node/runner/node_runner.go
Labels: Testing

#651 `TotalMembership` added in `CongressVotingResult`
  lib/client/response.go
  lib/common/url.go
  lib/transaction/operation/congress_voting_result.go
  lib/transaction/operation/operation_test.go
  lib/transaction/transaction_test.go
  tests/client/congressvoting_inflationpf_test.go
Labels: Urgent, enhancement

#780 Remove start isaacStateManager fitering
  lib/node/runner/node_runner.go
Labels: Urgent, bug, question

#793 Modify argument of proposeOrWait state -> round
  lib/node/runner/isaac_state_manager.go
Labels: Refactoring, bug

#748 BlockOperations save with BlockHeight prefix
  lib/block/operation.go
  lib/block/operation_test.go
  lib/common/prefix.go
Labels: API

#791 Fix `reverse=true`
  lib/storage/leveldb.go
  lib/storage/leveldb_test.go
Labels: API, Urgent

#790 Subscribe API
  lib/block/account.go
  lib/block/account_test.go
  lib/block/block.go
  lib/block/operation.go
  lib/block/test.go
  lib/block/transaction.go
  lib/block/transaction_pool.go
  lib/client/client.go
  lib/common/observer/observer.go
  lib/node/runner/api/account.go
  lib/node/runner/api/account_test.go
  lib/node/runner/api/api.go
  lib/node/runner/api/base_test.go
  lib/node/runner/api/blocks.go
  lib/node/runner/api/blocks_test.go
  lib/node/runner/api/operation.go
  lib/node/runner/api/operation_test.go
  lib/node/runner/api/stream.go
  lib/node/runner/api/stream_test.go
  lib/node/runner/api/transaction.go
  lib/node/runner/api/transaction_test.go
  lib/node/runner/api/tx_operations.go
  lib/node/runner/api/tx_operations_test.go
  lib/node/runner/checker.go
  lib/node/runner/node_runner.go
  lib/storage/statedb/state_object.go
  lib/transaction/operation/operation.go
  tests/client/account_test.go
  tests/client/congressvoting_inflationpf_test.go
  tests/client/const.go
  tests/client/freezing_test.go
  tests/client/test.go
  tests/client/transaction_status_test.go
Labels: API, Refactoring

#794 Fixed Panic Error: returned `RunningRound` is not found
  lib/consensus/isaac.go
  lib/node/runner/checker.go
Labels: Urgent, bug

#786 Add node flag for SEBAK_SYNC_CHECK_PREVBLOCK and refactoring
  cmd/sebak/cmd/run.go
  lib/sync/config.go
  lib/sync/fetcher.go
  lib/sync/syncer.go
  lib/sync/syncer_test.go
  lib/sync/validator.go
Labels: Refactoring, sync

#797 Add hash to infolog in finish ballot
  lib/node/runner/finish_ballot.go
Labels: enhancement

#763 operation index for target also
  lib/block/operation.go
  lib/client/response.go
  lib/common/prefix.go
  lib/node/runner/api/api.go
  lib/node/runner/api/base_test.go
  lib/node/runner/api/operation.go
  lib/node/runner/api/operation_test.go
  lib/node/runner/api/resource/operation.go
  lib/node/runner/api/transaction_test.go
  lib/node/runner/api/tx_operations_test.go
  lib/transaction/operation/operation.go
  tests/client/const.go
  tests/client/freezing_test.go
  tests/client/operation_test.go
Labels: Urgent, bug

#804 `/api/v1/accounts` supports to get multiple accounts at one request
  lib/node/runner/api/account.go
  lib/node/runner/api/account_test.go
  lib/node/runner/api/api.go
  lib/node/runner/api/base_test.go
  lib/node/runner/node_runner.go
Labels: Urgent, enhancement

#805 Self-signed ballot will use `network.MessageBroker` instead of `ballotBroadcastChannel`
  lib/network/memory.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/checker.go
  lib/node/runner/isaac_state_manager.go
  lib/node/runner/node_runner.go
Labels: Urgent, bug, enhancement

#812 Clean up txs in txpool when sync up
  cmd/sebak/cmd/run.go
  lib/node/runner/api_node_test.go
  lib/node/runner/finish_ballot_test.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/test.go
  lib/sync/config.go
  lib/sync/config_test.go
  lib/sync/fetcher.go
  lib/sync/validator.go
  lib/sync/validator_test.go
Labels: Urgent, bug, enhancement, sync

#803 Use first proposed time in sync and simple refactoring
  lib/common/constant.go
  lib/node/runner/isaac_state_manager.go
Labels: Refactoring, Urgent, bug

#809 Sync latest nodes
  lib/sync/config.go
  lib/sync/fetcher.go
  lib/sync/fetcher_test.go
  lib/sync/nodelist.go
  lib/sync/syncer.go
  lib/sync/syncer_test.go
  lib/sync/types.go
Labels: enhancement, sync

#816 Empty `X-SEBAK-RESULT-COUNT` header in apis
  lib/node/runner/api_block.go
  lib/node/runner/api_block_test.go
  lib/node/runner/api_transaction.go
Labels: Urgent, bug

#810 Set log output for HTTP request & response
  cmd/sebak/cmd/run.go
  lib/network/http2.go
  lib/network/http2_network_log.go
  lib/network/init.go
Labels: Urgent, enhancement

#773 Limit total operations in ballot
  cmd/sebak/cmd/run.go
  lib/common/config.go
  lib/common/constant.go
  lib/errors/errors.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/checker_ballot_transaction_test.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
Labels: Urgent, enhancement

#811 Prevent confirming different ballot
  lib/consensus/ballot_send_record.go
  lib/consensus/ballot_send_record_test.go
  lib/consensus/isaac.go
  lib/consensus/remove_running_round_test.go
  lib/node/runner/checker.go
  lib/node/runner/isaac_state_manager.go
  lib/node/runner/isaac_state_transit_test.go
  lib/node/runner/node_runner.go
Labels: Consensus, Urgent, bug

#818 Api query encoding/decoding and prev cursor patch
  lib/block/transaction_test.go
  lib/node/runner/api/account.go
  lib/node/runner/api/base_test.go
  lib/node/runner/api/blocks.go
  lib/node/runner/api/operation.go
  lib/node/runner/api/operation_test.go
  lib/node/runner/api/pagequery.go
  lib/node/runner/api/transaction.go
  lib/node/runner/api/transaction_test.go
  lib/node/runner/api/tx_operations.go
  lib/node/runner/api_block_test.go
  lib/storage/leveldb.go
  lib/storage/leveldb_test.go
  lib/transaction/operation/test.go
Labels: API, Urgent

#807 Clean up the THICK log messages
  lib/consensus/isaac.go
  lib/network/validator_connection_manager.go
  lib/node/runner/block_operations.go
  lib/node/runner/checker.go
  lib/node/runner/checker_message.go
  lib/node/runner/finish_ballot.go
  lib/node/runner/isaac_simulation_test.go
  lib/node/runner/isaac_voting_empty_transaction_test.go
  lib/node/runner/node_runner.go
Labels: enhancement

#774 add condition ratio for ricardian contract sample
  docs/ricardian._sample.yaml
Labels: Contract

#827 Remove cache middleware for GetNodeInfoHandler
  lib/node/runner/node_runner.go
Labels: API

#829 Fix to use LatestVotingBasis in NextRound()
  lib/consensus/isaac.go
  lib/node/runner/checker.go
  lib/node/runner/isaac_state_manager.go
Labels: Consensus, Urgent, bug

#837 Use bufio.Reader in place of bufio.Scanne for large data
  lib/sync/fetcher.go
  lib/sync/fetcher_test.go
Labels: Urgent, bug, sync

#835 Fixed to start consensus after nodes restarting simultaneously
  lib/network/connection_manager.go
  lib/network/validator_connection_manager.go
  lib/node/runner/checker.go
  lib/node/runner/checker_test.go
  lib/node/runner/node_runner.go
  lib/node/runner/test_connection_manager.go
  lib/sync/mock_test.go
Labels: bug

#841 Add conf fields in node_info API
  lib/node/info.go
  lib/node/runner/api/node_info.go
  lib/node/runner/api/node_info_test.go
  lib/node/runner/util.go
Labels: API

#843 Support CORS for node-info api
  lib/node/runner/node_runner.go
Labels: API

#752 Support JSONRPC for LevelDBBackend
  cmd/sebak/cmd/run.go
  docker/node1.env
  docker/node2.env
  docker/node3.env
  docker/node4.env
  docker/self.env
  go.mod
  go.sum
  lib/common/config.go
  lib/common/constant.go
  lib/node/runner/jsonrpc.go
  lib/node/runner/jsonrpc_test.go
  lib/node/runner/node_runner.go
  lib/storage/storage.go
Labels: enhancement

#845 Fix a bug about blocks api paging
  lib/node/runner/api/blocks.go
  lib/node/runner/api/blocks_test.go
  lib/node/runner/api/pagequery.go
  lib/node/runner/api/resource/resource.go
  lib/storage/leveldb.go
  lib/storage/leveldb_test.go
Labels: API, Urgent, bug

#849 remove self link for operation resource
  lib/node/runner/api/resource/operation.go
  lib/node/runner/api/resource/resource_test.go
Labels: bug

#839 Change IsValidVotingBasis to return the reason of the mismatch
  lib/consensus/isaac.go
  lib/node/runner/checker.go
Labels: enhancement

#853 Make blocks API default to reverse=true
  lib/node/runner/api/blocks.go
  lib/node/runner/api/pagequery.go
Labels: API
