Repository bosnet/sebak, pull requests merged in 2018-10, with the labels that each got.

#457 Operation CongressVoting
  lib/error/errors.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/transaction/operation.go
  lib/transaction/operation_congress_voting.go
  lib/transaction/operation_congress_voting_result.go
  lib/transaction/operation_test.go
Labels: Congress Voting

#467 Sync
  cmd/sebak/cmd/run.go
  lib/network/connection_manager.go
  lib/network/validator_connection_manager.go
  lib/node/runner/checker.go
  lib/sync/config.go
  lib/sync/config_test.go
  lib/sync/fetcher.go
  lib/sync/fetcher_test.go
  lib/sync/init.go
  lib/sync/logger.go
  lib/sync/mock_test.go
  lib/sync/pool.go
  lib/sync/pool_test.go
  lib/sync/syncer.go
  lib/sync/syncer_test.go
  lib/sync/try.go
  lib/sync/types.go
  lib/sync/validator.go
  lib/sync/validator_test.go
Labels: sync

#477 Make saving txs and running ops in one method
  lib/node/runner/checker.go
  lib/sync/validator.go
Labels: sync

#476 Waiting until prev block save, Remove localnode when pick fetch node
  lib/block/test.go
  lib/common/observer/observer.go
  lib/sync/config.go
  lib/sync/fetcher.go
  lib/sync/fetcher_test.go
  lib/sync/syncer.go
  lib/sync/syncer_test.go
  lib/sync/validator.go
  lib/sync/validator_test.go
Labels: sync

#469 Transaction Fee Will Go To Common (Budget) Account
  cmd/sebak/cmd/genesis.go
  cmd/sebak/cmd/run.go
  lib/ballot/ballot.go
  lib/ballot/ballot_test.go
  lib/ballot/proposer_transaction.go
  lib/block/block.go
  lib/block/block_test.go
  lib/block/test.go
  lib/common/constant.go
  lib/error/errors.go
  lib/node/runner/api_block.go
  lib/node/runner/api_node_test.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/isaac_state_manager.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/test.go
  lib/node/runner/test_connection_manager.go
  lib/node/runner/util.go
  lib/node/runner/util_test.go
  lib/transaction/operation.go
  lib/transaction/operation_collect_tx_fee.go
  lib/transaction/test.go
  lib/transaction/transaction.go
  lib/transaction/transaction_checker.go
  lib/transaction/transaction_test.go
  tests/run.sh
Labels: enhancement

#480 Add Syncer.SetSyncTargetHeight
  lib/sync/config.go
  lib/sync/config_test.go
  lib/sync/fetcher.go
  lib/sync/pool.go
  lib/sync/syncer.go
  lib/sync/syncer_test.go
  lib/sync/types.go
  lib/sync/validator.go
Labels: sync

#488 Syncer no incr height
  lib/sync/syncer.go
  lib/sync/syncer_test.go
Labels: sync

#493 Sync to use for validate tx `runner.ValidateTX`
  lib/sync/validator.go
Labels: sync

#483 Support Inflation In Every Block
  cmd/sebak/cmd/run.go
  lib/ballot/ballot.go
  lib/ballot/ballot_test.go
  lib/ballot/proposer_transaction.go
  lib/common/constant.go
  lib/common/inflation.go
  lib/consensus/isaac_configuration.go
  lib/error/errors.go
  lib/network/http2.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/block_time_test.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/checker_test.go
  lib/node/runner/isaac_state_manager.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/self_mode_test.go
  lib/node/runner/test.go
  lib/node/runner/util.go
  lib/node/runner/util_test.go
  lib/transaction/operation.go
  lib/transaction/operation_inflation.go
  tests/run.sh
  tests/utils.sh
Labels: enhancement

#494 Ordering txs by block.Transactions
  lib/sync/fetcher.go
Labels: sync

#491 Get Missing Transactions From Proposer
  lib/error/errors.go
  lib/network/base.go
  lib/network/connection_manager.go
  lib/network/http2_client.go
  lib/network/memory_client.go
  lib/node/runner/api_block.go
  lib/node/runner/api_transactions_test.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/checker_test.go
  lib/node/runner/node_runner.go
Labels: bug

#495 Changes SetSyncTargetBlock(ctx,height,nodeAddrs)
  lib/sync/fetcher.go
  lib/sync/syncer.go
  lib/sync/syncer_test.go
  lib/sync/types.go
Labels: sync

#498 Validating Incoming Transactions in API
  lib/block/block.go
  lib/block/block_test.go
  lib/common/router.go
  lib/common/router_test.go
  lib/error/errors.go
  lib/network/http2_client.go
  lib/network/httputils/http_problem.go
  lib/network/httputils/httputils.go
  lib/network/memory.go
  lib/network/validator_connection_manager.go
  lib/node/runner/api_message_handler_test.go
  lib/node/runner/api_node.go
  lib/node/runner/api_node_test.go
  lib/node/runner/api_transactions_test.go
  lib/node/runner/checker_message.go
  lib/node/runner/checker_message_test.go
  lib/node/runner/checker_test.go
  lib/node/runner/isaac_simulation_test.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
  lib/transaction/transaction.go
Labels: enhancement

#510 Add Middleware
  cmd/sebak/cmd/run.go
  lib/error/errors.go
  lib/network/base.go
  lib/network/http2.go
  lib/network/http_middlewares.go
  lib/network/http_middlewares_test.go
  lib/network/init.go
  lib/network/memory.go
  lib/node/runner/node_runner.go
Labels: API, enhancement

#513 Call syncer in consensus
  cmd/sebak/cmd/run.go
  docker/node4.env
  docker/self.env
  lib/consensus/isaac.go
  lib/consensus/isaac_test.go
  lib/node/runner/api_node_test.go
  lib/node/runner/api_transactions_test.go
  lib/node/runner/checker.go
  lib/node/runner/node_runner.go
  lib/node/runner/node_runner_test.go
  lib/node/runner/test.go
Labels: sync

#514 Add CORS Middleware for client API
  go.mod
  go.sum
  lib/node/runner/node_runner.go
Labels: API

#521 Patch for Irregular Incoming INIT Ballot
  lib/node/runner/checker.go
  lib/node/runner/checker_test.go
Labels: bug

#511 Node will have itself as validator
  cmd/sebak/cmd/cmd_test.go
  cmd/sebak/cmd/run.go
  cmd/sebak/common/util.go
  lib/node/local_node.go
Labels: enhancement

#522 Patched for missing Lock-Unlock
  lib/transaction/pool.go
Labels: bug

#523 Added time diff in `default_runner.sh`
  tests/default_runner.sh
Labels: enhancement

#519 Add sync flags to node cmd flags
  cmd/sebak/cmd/run.go
Labels: sync

#535 Adding Middleware In Base Router
  lib/network/http2.go
  lib/node/runner/node_runner.go
Labels: bug

#525 Support Rate Limit For API
  cmd/sebak/cmd/cmd_test.go
  cmd/sebak/cmd/run.go
  cmd/sebak/common/util.go
  go.mod
  go.sum
  lib/common/config.go
  lib/common/constant.go
  lib/common/net.go
  lib/error/errors.go
  lib/network/http_middlewares.go
  lib/network/http_middlewares_test.go
  lib/network/httputils/httputils.go
  lib/node/runner/node_runner.go
Labels: enhancement

#486 Integration Testing Env for SDK.
  .circleci/config.yml
  .gitignore
  Dockerfile_client.build
  docker/self.env
  lib/client/client.go
  lib/client/error.go
  lib/client/response.go
  tests/node/Dockerfile
  tests/node/README.md
  tests/node/account-creation/README.md
  tests/node/account-creation/request_1_2821_create_account_1.json
  tests/node/account-creation/request_1_2821_create_account_1.json.check
  tests/node/account-creation/request_2_2822_pay_to_account_1.json
  tests/node/account-creation/request_2_2822_pay_to_account_1.json.check
  tests/node/default_runner.sh
  tests/node/entrypoint.sh
  tests/node/overdraft/README.md
  tests/node/overdraft/request_1_2821_create_account_1.json
  tests/node/overdraft/request_1_2821_create_account_1.json.check
  tests/node/overdraft/request_2_2821_no_amount_tx.json
  tests/node/overdraft/request_2_2821_no_amount_tx.json.check
  tests/node/overdraft/request_3_2823_one_gon_payment.json
  tests/node/overdraft/request_3_2823_one_gon_payment.json.check
  tests/node/overdraft/request_4_2823_overdraft_by_99.json
  tests/node/overdraft/request_4_2823_overdraft_by_99.json.check
  tests/node/overdraft/request_5_2821_overdraft_by_1.json
  tests/node/overdraft/request_5_2821_overdraft_by_1.json.check
  tests/node/overdraft/request_6_2821_emptying_account.json
  tests/node/overdraft/request_6_2821_emptying_account.json.check
  tests/node/run.sh
  tests/node/utils.sh
  tests/sdk/Dockerfile
  tests/sdk/entrypoint.sh
  tests/sdk/main.go
  tests/sdk/run.sh
Labels: enhancement

#526 add prefix for resource link
  docs/v1/models.md
  lib/network/api/operation.go
  lib/network/api/resource/account.go
  lib/network/api/resource/constant.go
  lib/network/api/resource/operation.go
  lib/network/api/resource/transaction.go
  lib/network/api/resource/transaction_history.go
  lib/network/api/transaction.go
  lib/network/api/tx_operations.go
Labels: API

#427 filter type for operation API
  lib/block/operation.go
  lib/network/api/operation.go
  lib/network/api/operation_test.go
  lib/transaction/operation/operation.go
Labels: enhancement

#547 Add pprof handlers
  cmd/sebak/cmd/run.go
  lib/network/http2.go
  lib/node/runner/init.go
  lib/node/runner/node_runner.go
Labels: enhancement

#433 Unfreezing request operation and unfreezing
  cmd/sebak/cmd/wallet.go
  cmd/sebak/cmd/wallet/unfreezeRequest.go
  lib/block/operation.go
  lib/common/constant.go
  lib/error/errors.go
  lib/node/runner/checker.go
  lib/node/runner/checker_ballot_transaction.go
  lib/node/runner/isaac_simulation_unfreezing_test.go
  lib/node/runner/test.go
  lib/transaction/operation/operation.go
  lib/transaction/operation/unfreezing_request.go
  lib/transaction/test.go
Labels: frozen

#554 ignore tests directory for unittest
  .circleci/config.yml
Labels: bug

#557 For pre-flight request of CORS, Add allow headers, options
  lib/node/runner/node_runner.go
Labels: API

#567 Return 404 In API Handlers
  lib/network/api/account_test.go
  lib/network/api/operation.go
  lib/network/api/operation_test.go
  lib/network/api/transaction_test.go
  lib/network/api/tx_operations.go
  lib/network/api/tx_operations_test.go
  lib/network/httputils/httputils.go
Labels: bug

#581 Add RouterNameDebug and RouterNameMetric
  lib/network/http2.go
  lib/node/runner/node_runner.go
Labels: API

#584 explicit json struct tag
  lib/ballot/ballot.go
  lib/block/account.go
  lib/block/block.go
  lib/block/header.go
  lib/block/operation.go
  lib/block/transaction.go
  lib/block/transaction_history.go
  lib/client/response.go
  lib/transaction/operation/collect_tx_fee.go
  lib/transaction/operation/operation_inflation.go
  lib/transaction/transaction.go
  tests/node/account-creation/request_1_2821_create_account_1.json
  tests/node/account-creation/request_2_2822_pay_to_account_1.json
  tests/node/overdraft/request_1_2821_create_account_1.json
  tests/node/overdraft/request_2_2821_no_amount_tx.json
  tests/node/overdraft/request_3_2823_one_gon_payment.json
  tests/node/overdraft/request_4_2823_overdraft_by_99.json
  tests/node/overdraft/request_5_2821_overdraft_by_1.json
  tests/node/overdraft/request_6_2821_emptying_account.json
Labels: enhancement

#593 Add MustWriteJSON for convenient API
  lib/network/api/account.go
  lib/network/api/operation.go
  lib/network/api/transaction.go
  lib/network/api/tx_operations.go
  lib/network/httputils/json.go
Labels: API

#604 Allow the additional tags in 'Content-Type' header like 'charset'
  lib/common/router.go
  lib/common/router_test.go
Labels: bug

#599 Support `leveldb.Batch` in `LevelDBBackend`
  lib/error/errors.go
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/checker.go
  lib/node/runner/finish_ballot_test.go
  lib/storage/batch.go
  lib/storage/batch_test.go
  lib/storage/leveldb.go
  lib/storage/storage.go
Labels: enhancement

#618 Add slice for adding order in Transaction.Pool
  lib/transaction/pool.go
Labels: enhancement

#616 Use LDB.Batch in place of LDB.Transaction in sync
  lib/sync/validator.go
Labels: enhancement, sync

#621 Patch for failure of`TestCheckInflationBlockIncrease`
  lib/node/runner/ballot_proposer_transaction_test.go
  lib/node/runner/isaac_state_manager.go
  lib/node/runner/isaac_state_transit_test.go
Labels: bug

#617 Exclude `BlockOperation` from block API
  lib/node/runner/api_block.go
  lib/node/runner/api_block_test.go
Labels: enhancement

#620 Save Transaction before `finishBallot()`
  lib/block/genesis.go
  lib/block/operation_test.go
  lib/block/transaction.go
  lib/block/transaction_history.go
  lib/block/transaction_pool.go
  lib/block/transaction_pool_test.go
  lib/block/transaction_test.go
  lib/common/prefix.go
  lib/node/runner/api/resource/resource_test.go
  lib/node/runner/api/resource/transaction_history.go
  lib/node/runner/api/test.go
  lib/node/runner/api/tx_operations_test.go
  lib/node/runner/api_block.go
  lib/node/runner/api_block_test.go
  lib/node/runner/api_node.go
  lib/node/runner/api_transaction.go
  lib/node/runner/api_transactions_test.go
  lib/node/runner/checker.go
  lib/node/runner/checker_message.go
  lib/node/runner/checker_test.go
  lib/sync/fetcher_test.go
  lib/sync/validator.go
  lib/transaction/transaction.go
Labels: enhancement
