Repository bosnet/sebak, pull requests merged in 2019-01, with the labels that each got.

#893 Save BlockTransaction and BlockOperation when sync
  lib/node/runner/finish_ballot.go
  lib/sync/fetcher.go
  lib/sync/types.go
  lib/sync/validator.go
Labels: Urgent, sync

#896 Reset si.Bts in fetch function
  lib/sync/fetcher.go
Labels: bug, sync

#894 Add auto detecting current dirs in integration-test
  tests/long-term/run.sh
Labels: Refactoring, Testing

#884 Use CallerFileHandler
  cmd/sebak/cmd/run.go
Labels: observability

#889 Support `leveldb.Snapshot` in jsonrpc
  lib/errors/errors.go
  lib/node/runner/jsonrpc.go
  lib/node/runner/jsonrpc_test.go
  lib/storage/leveldb.go
  lib/storage/snapshot.go
Labels: bug, enhancement

#880 add pester for retriable client
  go.mod
  go.sum
  lib/common/http2_client.go
  lib/network/http2.go
  lib/network/http2_test.go
Labels: Consensus, Networking

#863 tx resource contains operations
  lib/client/response.go
  lib/node/runner/api/api.go
  lib/node/runner/api/base_test.go
  lib/node/runner/api/resource/operation.go
  lib/node/runner/api/resource/resource_test.go
  lib/node/runner/api/resource/transaction.go
  lib/node/runner/api/stream.go
  lib/node/runner/api/transaction.go
  lib/node/runner/api/transaction_test.go
Labels: API, Doc

#908 Remove unused block prefixes
  lib/common/prefix.go
Labels: enhancement

#902 Log debug when receiving different height ballot
  lib/consensus/isaac.go
  lib/node/runner/checker.go
Labels: maintenance

#885 Support Time Sync
  cmd/sebak/cmd/run.go
  go.mod
  go.sum
  lib/common/constant.go
  lib/common/exec.go
  lib/common/init.go
  lib/common/log.go
  lib/common/time.go
  lib/node/runner/init_test.go
Labels: enhancement

#913 Updating go modules
  go.mod
  go.sum
Labels: enhancement
